name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - dev
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.61.0

          # Optional: working directory, useful for monorepos
          # working-directory: v2

          # Optional: golangci-lint command line arguments.
          # Note: exclude arguments, e.g. --exclude-files="my_file", will not affect the "typecheck" linter,
          # at least since v1.61.0 - use build tags instead.
          #args: --exclude-files="platforms/digispark/digispark_adaptor.go"

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true
